name: Auto trigger mch and backplane operators

on:
  push:
    branches:
    - release-*
    paths:
    - 'crds/**'

  workflow_dispatch:

jobs:
  notify-mch:
    runs-on: ubuntu-latest
    steps:
      # Sends a dispatch event to multiclusterhub-operator to trigger an update
      - name: Notify MCH
        uses: peter-evans/repository-dispatch@v1.1.3
        with:
          token: ${{ secrets.HUB_OPERATOR_TOKEN }}
          repository: open-cluster-management/multiclusterhub-operator
          event-type: crd-change
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "repository": "${{ github.repository }}"}'
 
  notify-backplane:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Backplane
        uses: peter-evans/repository-dispatch@v1.1.3
        with:
          token: ${{ secrets.HUB_OPERATOR_TOKEN }}
          repository: open-cluster-management/backplane-operator
          event-type: crd-change
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "repository": "${{ github.repository }}"}'
          