# This is a basic workflow to help you get started with Actions

name: Update 2.3 Community CRDs

# Controls when the action will run. 
on:
  # Triggers the workflow to run every day
  schedule:
    - cron: "0 0 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.FF_TOKEN }}
          ref: release-2.3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # Runs a set of commands using the runners shell
      - name: Update Community CRDs
        run: |
          echo Upgrading pip
          python -m pip install --upgrade pip
          echo Installing script requirements
          python -m pip install -r scripts/cron-update-crds/requirements.txt
          python scripts/cron-update-crds/update-crds.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          signoff: true
          branch: "update-crds-2.3"
          delete-branch: true
          title: "Auto-Update CRDs [2.3]"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          labels: do-not-merge/hold
          assignees: cameronmwall,JakobGray,zkayyali812 
